manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: bildermankawasaki
      url-base: https://github.com/bildermankawasaki
    - name: dhruvinsh
      url-base: https://github.com/dhruvinsh
    - name: m165437
      url-base: https://github.com/M165437
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-keyboard-totem
      remote: bildermankawasaki
      revision: main
    - name: zmk-tri-state
      remote: dhruvinsh
      revision: main
    - name: nice-view-gem
      remote: m165437
      revision: main
  self:
    path: config
